# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
pandoc_version: 2.3.1
addons:
  chrome: stable
  apt:
    sources:
      - sourceline: 'ppa:cran/poppler'
    packages:
      - libpoppler-cpp-dev

before_install:
  - "curl https://xran.yihui.name/.gitconfig -o ~/.gitconfig"

before_script:
  - R CMD INSTALL .
  - Rscript tools/website.R

after_success:
  - "(curl https://xran.yihui.name/r-xran | bash)"
  - cd inst/examples; ./deploy_github
